# -*- coding: utf-8 -*-
{
    'name': "Import Morgan",
    'summary': """
        Manage Your Entire Training Operation""",
    'description': """
    """,
    'author': "Business Solution Advisors",
    'website': "http://www.bsa-me.com",
    'category': 'Website',
    'version': '0.11',
    'depends': [
        'base',
        'hr',
        'hr_payroll',
        'hr_attendance',
        'hr_recruitment',
        'hr_expense',
        'hr_holidays',
        'note',
        'mass_mailing_sms',
        'social',
        'website_sale',
        'board',
        'website_event',
        'website_event_questions',
        'website_event_track',
        'survey',
        'purchase',
        'sale_management',
        'crm',
        'account_accountant',
        'account',
        'hr_expense',
        'documents',
        'hr_skills',
        'hr_skills_slides',
        'hr_skills_survey',
        'stock',
        'stock_barcode',
        'contacts',
        'timesheet_grid',
        'survey',
        'mass_mailing',
        'sale_crm',
        'website_slides',
        'website_forum',
        'marketing_automation',
        'delivery',
        'website_sale_delivery'
    ]
}
