# -*- coding: utf-8 -*-
{
    'name': "Training",
    'summary': """
        Manage Your Entire Training Operation""",
    'description': """
    """,
    'author': "Business Solution Advisors",
    'website': "http://www.bsa-me.com",
    'category': 'Website',
    'version': '0.11',
    'depends': [
        'base',
        'hr',
        'hr_payroll',
        'hr_attendance',
        'hr_recruitment',
        'hr_expense',
        'hr_holidays',
        'note',
        'mass_mailing_sms',
        'social',
        'website_sale',
        'board',
        'website_event',
        'website_event_questions',
        'website_event_track',
        'survey',
        'purchase',
        'sale_management',
        'crm',
        'account_accountant',
        'account',
        'hr_expense',
        'documents',
        'hr_skills',
        'hr_skills_slides',
        'hr_skills_survey',
        'stock',
        'stock_barcode',
        'stock_account',
        'contacts',
        'timesheet_grid',
        'survey',
        'mass_mailing',
        'sale_crm',
        'website_slides',
        'website_forum',
        'marketing_automation',
        'delivery',
        'website_sale_delivery',
        'product_bundle_pack',
        'sale_coupon',
        'im_livechat',
        'event_sale',
        'account_reports'
    ],
    'data': [
        'security/groups.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        'views/data.xml',
        'views/views.xml',
        'views/templates.xml',
        'views/employee.xml',
        'views/event.xml',
        'views/survey.xml',
        'views/operationhub.xml',
        'views/course.xml',
        'views/menu_items.xml',
        'views/campaign.xml',
        'views/lead.xml',
        'views/company.xml',
        'views/sessions.xml',
        'views/res_partner.xml',
        #'views/assets.xml',
        'views/resume_line_type.xml',
        'views/resume_line.xml',
        'views/sale_order.xml',
        'views/ir_sequence.xml',
        'wizard/event_track_create_timesheet.xml',
        'data/salary_structure.xml',
        'data/server_actions.xml',
        'data/session_sale_data.xml',
        'data/templates.xml',
        'data/scheduled_actions.xml',
        'data/crm_stages.xml',
        #'data/update_menu.xml',
        'data/activity_type.xml',
        'wizard/session_edit_registration.xml',
        'wizard/event_configurator_views.xml',
        'wizard/purchase_comment_wizard.xml',
        'wizard/crm_opportunity_to_quotation.xml',
        'wizard/payslip_reject_reason.xml',
        #'views/payslip.xml',
        'views/purchase.xml',
        'data/paper_formats.xml',
        'views/reports.xml',
        'views/carrier.xml',
        'views/account_journal.xml',
        'views/mailing.xml',
        'views/account_move.xml',
        'views/sale_coupon_program.xml',
        'views/slide_slide.xml',
        'views/pricelist_item.xml',
        #'views/survey_question.xml',
        'views/stock_quant.xml',
        #'views/stock_move_line.xml',
        'views/documents.xml',
        #'views/calendar_event.xml',
        'views/product_registration.xml',
        'views/utm_campaign.xml',
        'views/hr_expense.xml',
        'views/res_partner_bank.xml',
        'views/hr_attendance.xml',
        'views/event_sale_configurator.xml',
        'wizard/account_move_reversal.xml',
        'wizard/event_transfer_dropout.xml',
        'wizard/account_payment_register.xml',
        'views/event_registration.xml',
        #'views/survey_answer.xml',
        'views/stock_picking.xml',
        'views/stock_valuation_layer.xml',
        

        #'views/account_payment.xml'
    ],
    'application': True,
    'assets': {
        'web.assets_backend': [
            'education/static/src/js/event_configurator_widget.js',
        ],
    },
}
